import type { WishRecord } from "@/lib/wish-wall";

export const wishSeed: WishRecord[] = [
  {
    id: "wish-001",
    nickname: "Ariel",
    displayName: "Ariel",
    wishText:
      "希望明年敢报名区域演讲比赛，也能把每次即兴练到更自然更真诚。",
    track: "演讲成长",
    status: "pending",
    pinned: false,
    sensitiveHit: false,
    anonymous: false,
    hue: "sky",
  },
  {
    id: "wish-002",
    nickname: "Mango",
    displayName: "匿名朋友",
    wishText:
      "愿新一年把拖延换成行动，把每次想做的事都往前推一小步。",
    track: "年度愿景",
    status: "approved",
    pinned: true,
    sensitiveHit: false,
    anonymous: true,
    hue: "aurora",
  },
  {
    id: "wish-003",
    nickname: "Sunny",
    displayName: "Sunny",
    wishText:
      "想把英文主持练稳，也带更多第一次来的伙伴更放松地站上台。",
    track: "会议主持",
    status: "approved",
    pinned: false,
    sensitiveHit: false,
    anonymous: false,
    hue: "gold",
  },
  {
    id: "wish-004",
    nickname: "Echo",
    displayName: "Echo",
    wishText:
      "愿工作、表达和生活都更从容，给家人和自己更多耐心与笑容。",
    track: "生活平衡",
    status: "approved",
    pinned: false,
    sensitiveHit: false,
    anonymous: false,
    hue: "sky",
  },
  {
    id: "wish-005",
    nickname: "Mia",
    displayName: "Mia",
    wishText:
      "希望学会更勇敢地赞美别人，也更坦然地接住属于自己的掌声。",
    track: "自我表达",
    status: "hidden",
    pinned: false,
    sensitiveHit: false,
    anonymous: false,
    hue: "rose",
  },
  {
    id: "wish-006",
    nickname: "Mori",
    displayName: "匿名朋友",
    wishText:
      "想在明年认识更多同频伙伴，一起把普通周三过成值得期待的小节日。",
    track: "社群连接",
    status: "approved",
    pinned: false,
    sensitiveHit: false,
    anonymous: true,
    hue: "aurora",
  },
  {
    id: "wish-007",
    nickname: "Forest",
    displayName: "Forest",
    wishText:
      "希望把中文演讲内容整理成系列分享，留下俱乐部这一年的火花。",
    track: "内容沉淀",
    status: "rejected",
    pinned: false,
    sensitiveHit: true,
    anonymous: false,
    hue: "gold",
  },
  {
    id: "wish-008",
    nickname: "Nova",
    displayName: "Nova",
    wishText:
      "愿明年能完成半马，也把每一次上台都跑成自己喜欢的节奏。",
    track: "身体与舞台",
    status: "pending",
    pinned: false,
    sensitiveHit: false,
    anonymous: false,
    hue: "rose",
  },
  {
    id: "wish-009",
    nickname: "Liam",
    displayName: "Liam",
    wishText:
      "希望每次点评都更具体温柔，让别人听见鼓励也听见方向。",
    track: "反馈能力",
    status: "approved",
    pinned: false,
    sensitiveHit: false,
    anonymous: false,
    hue: "sky",
  },
  {
    id: "wish-010",
    nickname: "Iris",
    displayName: "匿名朋友",
    wishText:
      "想在新一年多做几次即兴挑战，把紧张慢慢练成真诚和松弛。",
    track: "即兴表达",
    status: "approved",
    pinned: true,
    sensitiveHit: false,
    anonymous: true,
    hue: "aurora",
  },
  {
    id: "wish-011",
    nickname: "Luna",
    displayName: "Luna",
    wishText:
      "希望新一年能把博客和播客都启动，让表达不只留在会议那一晚。",
    track: "个人项目",
    status: "pending",
    pinned: false,
    sensitiveHit: false,
    anonymous: false,
    hue: "gold",
  },
  {
    id: "wish-012",
    nickname: "Stone",
    displayName: "Stone",
    wishText:
      "愿明年能更稳定地主持双语会议，把节奏和情绪都接得更稳。",
    track: "双语主持",
    status: "approved",
    pinned: false,
    sensitiveHit: false,
    anonymous: false,
    hue: "sky",
  },
  {
    id: "wish-013",
    nickname: "River",
    displayName: "River",
    wishText:
      "想在新的十二个月里多给身边人拥抱，也给自己更多休息许可。",
    track: "关系与疗愈",
    status: "approved",
    pinned: false,
    sensitiveHit: false,
    anonymous: false,
    hue: "rose",
  },
  {
    id: "wish-014",
    nickname: "Sora",
    displayName: "匿名朋友",
    wishText:
      "希望明年继续留在这个俱乐部，也见证更多新人第一次闪闪发光。",
    track: "俱乐部记忆",
    status: "approved",
    pinned: false,
    sensitiveHit: false,
    anonymous: true,
    hue: "gold",
  },
];

export const screenPlacements = [
  { top: "13%", left: "6%", width: "17rem", rotation: -7, delay: "0s", duration: "17s" },
  { top: "10%", left: "28%", width: "18rem", rotation: 5, delay: "1.4s", duration: "18s" },
  { top: "17%", left: "53%", width: "17rem", rotation: -4, delay: "2.2s", duration: "16s" },
  { top: "13%", left: "75%", width: "15rem", rotation: 6, delay: "0.7s", duration: "19s" },
  { top: "46%", left: "8%", width: "18rem", rotation: -5, delay: "1.8s", duration: "17s" },
  { top: "42%", left: "31%", width: "17rem", rotation: 4, delay: "2.8s", duration: "18s" },
  { top: "49%", left: "55%", width: "18rem", rotation: -3, delay: "0.9s", duration: "16s" },
  { top: "44%", left: "78%", width: "15rem", rotation: 5, delay: "3.1s", duration: "18s" },
];

export const previewSummary = {
  submitted: 24,
  approved: 9,
  pending: 4,
  rejected: 1,
  hidden: 1,
  pinned: 2,
  devices: 17,
};
